### ISSUE TITLE
TODO - GitHub Actions

### ISSUE THREAD

**Issue by greluc** [rjcncpt/StarCitizen-Deutsch-INI#316]
TODOs für die Automatisierung mittels GitHub Actions.

- [x] Commit im Release anpassen.
- [x] Changelog über [Compare-Link](https://github.com/rjcncpt/StarCitizen-Deutsch-INI/compare/07.12.23-PTU...TEST-PTU) automatisieren
- [x] Release Sortierung fixen. (GitHub sortiert die Releases anhand SemVer-Benennung der Tags und Releases und erst nachrangig nach Datum/Uhrzeit)
- [ ] Weitere Fehlerfälle bei Commit-Titel abfangen.
- [x] Kommentare für Maintainer
- [ ] Pfade als Variable (Environment?)
- [x] #431
- [x] #432
- [x] #448
