### ISSUE TITLE
TODO - Grundsätzliche Neuübersetzung

### ISSUE THREAD

**Issue by rjcncpt** [rjcncpt/StarCitizen-Deutsch-INI#405]
# TODO - Grundsätzliche Neuübersetzung

### Untertitel Rework
Professionelles und vollständiges Rework aller Untertitel. Wir haben 199 Datensätze, die rund 16.000 Zeilen umfassen.
- [x] Erledigt: 101 Datensätze
- [ ] Offen: 98 Datensätze

### Aktuell in Arbeit
- [ ] Untertitel Rework

### Offen
- [ ] `mg_miles_collectcargo_`
- [ ] `mg_miles_delivercargo_`
- [ ] `mg_miles_planetcollect_`
- [ ] `mg_miles_recoverStolen_`
- [ ] `mg_miles_spacecollect_`
- [ ] `mg_miles_sweeplegal_`
- [ ] Descriptions (Magazine und co.) Manchmal Zahl als Text manchmal als Zahl. Vereinheitlichen?

### Offen - Klingen an manchen Stellen komisch (nicht immer). Nur die Anfangssätze überarbeiten.
- [ ] `hurston_bounty_`

### Sontige (mal drüber schauen)
- [ ] `Item_Desc`
- [ ] `item_Mining_`
- [ ] `item_fuel`
- [ ] `item_salvage`
- [ ] `item_scraper_`

### Erledigt
- [x] `hurston_RetrieveConsignment_`
- [x] `hurston_recoverspace_`
- [x] `hurston_sectorsweep_`
- [x] `hurston_hackprevent_`
- [x] `hurston_destroyprobe_`
- [x] `hurston_destroyblade_`
- [x] `hurston_basesweep_`
- [x] `hurston_assassination_`
- [x] `hurston_UGF`
- [x] `mg_miles_capturegang_` #538 
- [x] `mg_battaglia_mining_` #520
- [x] `mg_battaglia_invite_` #520
- [x] `Dlg_SC_mc_` (Kommt mit 3.23 LIVE)
- [x] `mg_miles_blackboxlegal_` #520
- [x] `mg_miles_blackboxillegal_` #520
- [x] `mg_miles_assassin_` #520
- [x] `mg_miles_MissingPerson_` #520
- [x] `Hints_` #520
- [x] `mg_klim_` #520
- [x] `mg_pacheco_` #520
- [x] `manufacturer_Desc` #520
- [x] `item_commodities_` #520
- [x] `items_commodities_` #520
- [x] `vehicle_Desc` #520
- [x] `pause_`, `UI`, `HUD` #520
- [x] `Covalex_` #520
- [x] `headhunters_` #509 #512 
- [x] `kareah_datapad_` #508
- [x] `kareahsweep_` #510
- [x] `hdactivist_` #507
- [x] `bounty_` #506 
- [x] `crusader_` #469
- [x] `OEM_UI_` #490 ...
- [x] `Retrievedatapad`
- [x] `MissingPersons_Crew`
- [x] `TarPits_`
- [x] `Adagio_`
- [x] `ProtLife_`
- [x] `ServiceBeacon_`
- [x] `BHG_Certification_`
- [x] `BHG_ReputationJournal_`
- [x] `shubin_claimsweep_`
- [x] `blacjac_bounty_`
- [x] `blacjac_destroystash_`
- [x] `blacjac_destroyprobe_`
- [x] `spacecargo_illegal_`
- [x] `spacecargo_legal_`
- [x] `spacesteal_desc_`
- [x] `cfp_delivery_`
- [x] `cfp_destroy_`
- [x] `cfp_salvage_`
- [x] `cfp_searchbody_`
- [x] `cdf_openbounty_`
- [x] `FTL_delivery_desc_`
- [x] `missionManager_`
- [x] `bitzeros_`
- [x] `mgClovus_`
- [x] `mg_clovus_`
- [x] `mg_ruto_` (Der komplette Block)
- [x] `mg_battaglia_blackbox_`
- [x] `mg_battaglia_claimsweep_desc_`
- [x] `mg_battaglia_deliver_`
- [x] `mg_battaglia_escort_`
- [x] `mg_battaglia_intro_`
- [x] `mg_battaglia_recover_`
- [x] `mg_battaglia_search_body_`
- [x] `mg_battaglia_search_crew_`
- [x] `mg_battaglia_sectorsweep_`
- [x] `mg_miles_bounty_desc_`
- [x] `meet_miles_`
- [x] `dusters_claimsweep`
- [x] `destroyblade_`
- [x] `destoryitems_`
- [x] `destroyprobe_`
- [x] `destroyprobeillegal_`
- [x] `destroyprobelegal_`
- [x] `searchbody_desc_`
- [x] `searchcrew_desc_`
- [x] `sectorsweep_desc_`
- [x] `planetcollect_drug_`
- [x] `planetcollect_food_`
- [x] `planetcollect_illegalwaste_`
- [x] `planetcollect_legal_`
- [x] `planetcollect_meds_`
- [x] `planetcollect_ore_`
- [x] `planetcollect_oresamp_`
- [x] `planetcollect_research_`
- [x] `planetcollect_seeds_`
- [x] `planetcollect_steal_`
- [x] `planetcollect_waste`
- [x] `destroystash_`
- [x] `blacjac_destroystash_desc_`
- [x] `recoverstolen_desc`
- [x] `recoverstolen_space`
- [x] `blacjac_hackprevent_desc_`
- [x] `blacjac_recoverspace_desc_`
- [x] `redwind_Danger_`
- [x] `redwind_SignOff_`
- [x] `redwind_Timed_`
- [x] `redwind_delivery_desc`
- [x] `RedWind_Delivery_Illegal_Desc_`
- [x] `RedWind_LocalDelivery_desc_`
- [x] `blackboxillegal_`
- [x] `blackboxlegal_`
- [x] `distraction_desc_`
- [x] `distraction_wanted_`
- [x] `distractionkill_desc_`
- [x] `cfp_recovery_desc_`
- [x] `cfp_searchbody_`
- [x] `Crusader_ReputationJournal_`
- [x] `Hurston_ReputationJournal_`
- [x] `DXSM_MCCV_INDI_SM_Simulator_Announcer_`
